### ISSUE TITLE
Parse Markdown blockquotes

### ISSUE THREAD

**Issue by corywatilo** [PostHog/squeak-react#48]
Squeak! supports some Markdown, but apparently not the syntax for blockquotes

[example](https://posthog.com/docs/user-guides/organizations-and-projects#questions)

<img width="700" alt="image" src="https://user-images.githubusercontent.com/154479/172842239-f0e8c170-47b5-4cc8-ad91-45702d7fe516.png">

**Comment by pjhul** [comment]
Closing this as we've moved squeak-react into the [Squeak](https://github.com/PostHog/squeak) repo and I've moved the issue there 👍
